### ISSUE TITLE
What were the QEMU bugs?

### ISSUE THREAD

**Issue by polarathene** [whitequark/rust-vnc#5]
You mentioned that your client worked around some QEMU bugs, but you don't mention what any of them were. Just curious what those might be?

**Comment by whitequark** [comment]
Some weird stream corruptions. Blocks would be dropped seemingly at random when they should have been refreshed after, say, moving the mouse over them, glitched out display, stuff like that. I dunno what the actual bug is, what little I've seen of QEMU VNC code seemed sane.
